joes_pizza/config/routes.rb
Rails.application.routes.draw do
  get 'user/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'recipe#index'

  resources :users
  resources :pizza
  resources :recipe

  resources :order
  resources :users do
    resources :order
  end
end

joes_pizza/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

joes_pizza/app/models/crust.rb
class Crust < ApplicationRecord
end

joes_pizza/app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

joes_pizza/app/models/delivery_info.rb
class DeliveryInfo < ApplicationRecord
  validates :address1, presence: true
  validates :address2, presence: true
  validates :phone, presence: true
  validates :phone, numericality: true
end

joes_pizza/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipeingredient
  has_many :recipe, through: :recipeingredients
end

joes_pizza/app/models/order.rb
class Order < ApplicationRecord
  has_many :pizzas

  def index

  end
end

joes_pizza/app/models/pizza.rb
class Pizza < ApplicationRecord
  has_one :crust
  belongs_to :recipe
  belongs_to :order
end

joes_pizza/app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :pizzas
  has_many :recipeingredients
  has_many :ingredients, through: :recipeingredients
end

joes_pizza/app/models/recipeingredient.rb
class Recipeingredient < ApplicationRecord
  has_one :pizza
  belongs_to :ingredient
end

joes_pizza/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

joes_pizza/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email])
  end
end

joes_pizza/app/controllers/order_controller.rb
class OrderController < ApplicationController
  def index
    @orders = Order.where(user_id: params[:user_id])
    @user = User.find(params[:user_id])
  end
end

joes_pizza/app/controllers/pizza_controller.rb
class PizzaController < ApplicationController
  def index
    @pizzas = Pizza.all
  end

  def show
    @pizza = Pizza.find(params[:id])
  end
end

joes_pizza/app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

joes_pizza/app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  end
end

joes_pizza/app/helpers/application_helper.rb
module ApplicationHelper
end

joes_pizza/app/helpers/order_helper.rb
module OrderHelper
end

joes_pizza/app/helpers/pizza_helper.rb
module PizzaHelper
end

joes_pizza/app/helpers/recipe_helper.rb
module RecipeHelper
end

joes_pizza/app/helpers/user_helper.rb
module UserHelper
end

joes_pizza/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Social Forum</a> -->
      <%= link_to 'Joe\'s Pizza', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
        <!--<li><a href="#">Link</a></li> -->
        <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>-->
      </ul>
      <!--<form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
      <ul class="nav navbar-nav navbar-right">
        <% unless user_signed_in?%>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% else %>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to current_user.first_name.to_s, current_user %></li>
          <li><%= link_to 'My Orders', user_order_index_path(current_user) %></li>
        <% end %>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

joes_pizza/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JoesPizza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="fluid-container">
      <%= render 'layouts/header' %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

joes_pizza/app/views/order/index.html.erb
<h1>Orders from <%= @user.first_name + ' ' + @user.last_name %></h1>

joes_pizza/app/views/order/show.html.erb
<h1>Orders from <%= @user.first_name + ' ' + @user.last_name %></h1>

joes_pizza/app/views/recipe/index.html.erb
<h1>Menu</h1>

<% @recipes.each do |recipe| %>
  <div class="col-md-3 pizza-item">
    <h2><%= link_to recipe.name , recipe %></h2>
    <p><%= number_to_currency recipe.price %></p>
  </div>
<% end %>

joes_pizza/app/views/recipe/show.html.erb
<h1><%= @recipe.name %></h1>

<h2>Ingredients</h2>

<div class="col-md-4">
  <ul>
    <% @recipe.recipeingredients.each do |ingredient| %>
      <li><%= ingredient.ingredient.name %></li>
    <% end %>
  </ul>

<h2>Base price: <%= number_to_currency @recipe.price %></h2>
  <h2><%= link_to 'Add to Cart' , root_path %></h2>
</div>

joes_pizza/app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>